### ISSUE TITLE
Resource Page Experience

### ISSUE THREAD

**Issue by justsanchez** [justsanchez/FESonline.github.io#8]
### Resource Page Overview
A page that's full of valuable resources for a student (CompSci, Bio, Medicine...)

Page can contain:
- Interview Prep (Descriptions and Links to videos)
- Resume Tips
- Application Window 
    - When to start applying, companies to look for (AMAZON, LENOVO, NCINO, OHANAFY)
- Scholarships (Maybe a whole other page that's connected to the resources page)  (Javi, April insights maybe helpful) 
- _And the list can continue..._

Requirements:
- Will need to make a whole complete HTML/CSS file, _@justsanchez will help set up_
- Try your best to follow the design flow and carry it to the new page

Help Notes:
- Look for several resource pages that can help inspire and kick off the development process

Branch name: **resourcesPage**
- The branch should contain the starter files in making the resources page experience

**Comment by DiegoRV07** [comment]
Finished the page. Committed to main today
